import {
  faCar,
  faTachometerAlt,
  faGasPump,
  faCalendarAlt,
  faExchangeAlt,
  faCircle,
  faCog,
  faTint,
  faTruck,
  faPaintBrush,
  faFileAlt,
} from '@fortawesome/free-solid-svg-icons';

export const carData = [
  {
    id: 1,
    name: 'Toyota Camry New',
    description: '3.5 D5 PowerPulse Momentum 5dr AWD',
    price: '$40,000',
    imageUrl: '/assets/carListImage.svg',
    images: [
      '/assets/carListImage.svg',
      '/assets/carListImage.svg',
      '/assets/carListImage.svg',
      '/assets/carListImage.svg',
    ],
    mileage: '250',
    fuel: 'Petrol',
    transmission: 'Manual',
  },
  {
    id: 2,
    name: 'Honda Accord',
    description: '2.0 Turbocharged Sedan',
    price: '$30,000',
    imageUrl: '/assets/carListImage.svg',
    images: [
      '/assets/carListImage.svg',
      '/assets/carListImage.svg',
      '/assets/carListImage.svg',
      '/assets/carListImage.svg',
    ],
  },
  {
    id: 3,
    name: 'BMW M4',
    description: 'Sports Coupe with Luxury',
    price: '$80,000',
    imageUrl: '/assets/carListImage.svg',
    images: [
      '/assets/carListImage.svg',
      '/assets/carListImage.svg',
      '/assets/carListImage.svg',
      '/assets/carListImage.svg',
    ],
    mileage: '250',
    fuel: 'Petrol',
    transmission: 'Manual',
  },
  {
    id: 4,
    name: 'Audi A6',
    description: 'Luxury Sedan with advanced features',
    price: '$50,000',
    imageUrl: '/assets/carListImage.svg',
    images: [
      '/assets/carListImage.svg',
      '/assets/carListImage.svg',
      '/assets/carListImage.svg',
      '/assets/carListImage.svg',
    ],
    mileage: '250',
    fuel: 'Petrol',
    transmission: 'Manual',
  },

  {
    id: 5,
    name: 'Mercedes-Benz C-Class',
    description: 'Compact luxury sedan with high-tech features',
    price: '$45,000',
    imageUrl: '/assets/carListImage.svg',
    images: [
      '/assets/carListImage.svg',
      '/assets/carListImage.svg',
      '/assets/carListImage.svg',
      '/assets/carListImage.svg',
    ],
    mileage: '250',
    fuel: 'Petrol',
    transmission: 'Manual',
  },
  {
    id: 6,
    name: 'Ford Mustang',
    description: 'Iconic American Muscle Car',
    price: '$55,000',
    imageUrl: '/assets/carListImage.svg',
  },
  {
    id: 7,
    name: 'Chevrolet Camaro',
    description: 'Powerful sports coupe with cutting-edge tech',
    price: '$50,000',
    imageUrl: '/assets/carListImage.svg',
  },
  {
    id: 8,
    name: 'Tesla Model 3',
    description: 'All-electric performance sedan',
    price: '$55,000',
    imageUrl: '/assets/carListImage.svg',
  },
  {
    id: 9,
    name: 'Porsche 911',
    description: 'Luxury sports car with premium performance',
    price: '$90,000',
    imageUrl: '/assets/carListImage.svg',
  },
  {
    id: 10,
    name: 'Nissan Altima',
    description: 'Comfortable mid-size sedan with reliable features',
    price: '$25,000',
    imageUrl: '/assets/carListImage.svg',
  },
  {
    id: 11,
    name: 'Jaguar F-Type',
    description: 'Luxury sports coupe with stylish design',
    price: '$70,000',
    imageUrl: '/assets/carListImage.svg',
  },
  {
    id: 12,
    name: 'Mazda MX-5 Miata',
    description: 'Lightweight roadster with sporty handling',
    price: '$30,000',
    imageUrl: '/assets/carListImage.svg',
  },
  {
    id: 13,
    name: 'Lexus RX 350',
    description: 'Luxury SUV with modern features',
    price: '$55,000',
    imageUrl: '/assets/carListImage.svg',
  },
  {
    id: 14,
    name: 'Honda Civic',
    description: 'Reliable compact car with fuel efficiency',
    price: '$20,000',
    imageUrl: '/assets/carListImage.svg',
  },
  {
    id: 15,
    name: 'Subaru Outback',
    description: 'All-wheel drive wagon with off-road capability',
    price: '$35,000',
    imageUrl: '/assets/carListImage.svg',
  },
  {
    id: 16,
    name: 'Kia Stinger',
    description: 'Sporty sedan with sleek design and turbocharged power',
    price: '$40,000',
    imageUrl: '/assets/carListImage.svg',
  },
];

export const carDetail = {
  id: 1,
  name: 'Toyota Camry New',
  description: '3.5 D5 PowerPulse Momentum 5dr AWD Geartronic Estate',
  price: '$40,000',
  imageUrl: '/assets/cardPic.svg',
  body: 'Sedan',
  mileage: '250',
  fuelType: 'Petrol',
  year: '2021',
  transmission: 'Manual',
  driveType: 'Rear-Wheel Drive',
  condition: 'New',
  cylinder: '3.5',
  engineSize: '4 Doors Type',
  door: '12',
  color: 'Black, Blue, White',
  vin: 'MC812318',
};

export const carAttributes = [
  { icon: faCar, label: 'Body', value: carDetail.body },
  { icon: faTachometerAlt, label: 'Mileage', value: carDetail.mileage + ' km' },
  { icon: faGasPump, label: 'Fuel Type', value: carDetail.fuelType },
  { icon: faCalendarAlt, label: 'Year', value: carDetail.year },
  { icon: faExchangeAlt, label: 'Transmission', value: carDetail.transmission },
  { icon: faCircle, label: 'Drive Type', value: carDetail.driveType },
  { icon: faCog, label: 'Condition', value: carDetail.condition },
  { icon: faTint, label: 'Cylinder', value: carDetail.cylinder },
  { icon: faTruck, label: 'Engine Size', value: carDetail.engineSize },
  { icon: faTruck, label: 'Door', value: carDetail.door },
  { icon: faPaintBrush, label: 'Color', value: carDetail.color },
  { icon: faFileAlt, label: 'VIN', value: carDetail.vin },
];
export const dealer = {
  name: 'admin',
  address: '943 Broadway, Brooklyn',
  phone: '+88-123456789',
  profileImageUrl: '/assets/profilePicture.svg',
};
