import {
  faCar,
  faTachometerAlt,
  faGasPump,
  faCalendarAlt,
  faExchangeAlt,
  faCircle,
  faCog,
  faTint,
  faTruck,
  faPaintBrush,
  faFileAlt,
} from '@fortawesome/free-solid-svg-icons';

export const CARS_DATA = [
  {
    id: 1,
    name: '2017 BMW X5 xDrive35i',
    make: 'BMW',
    model: 'X5',
    slug: '2017-bmw-x5-xdrive35i',
    description:
      'Luxury AWD SUV with 3rd Row, Panoramic Roof, Navigation & Premium Package',
    price: '$22,500',
    imageUrl: '/cars/car0.jpeg',
    images: [
      '/cars/car0.jpeg',
      '/cars/car2.jpeg',
      '/cars/car3.jpeg',
      '/cars/car4.jpeg',
      '/cars/car5.jpeg',
      '/cars/car6.jpeg',
      '/cars/car7.jpeg',
      '/cars/car8.jpeg',
      '/cars/car9.jpeg',
    ],
    body: 'SUV',
    mileage: '113,388',
    fuelType: 'Gasoline',
    year: '2017',
    transmission: 'Automatic',
    driveType: 'All-Wheel Drive',
    condition: 'Used',
    cylinder: '6',
    engineSize: '3.0L Turbocharged',
    door: '4',
    color: 'Mineral White / Canberra Beige',
    vin: '5UXKR0C53H0U53898',
    attributes: [
      { icon: faCar, label: 'Body', value: 'SUV' },
      { icon: faTachometerAlt, label: 'Mileage', value: '113,388 mi' },
      { icon: faGasPump, label: 'Fuel Type', value: 'Gasoline' },
      { icon: faCalendarAlt, label: 'Year', value: '2017' },
      { icon: faExchangeAlt, label: 'Transmission', value: 'Automatic' },
      { icon: faCircle, label: 'Drive Type', value: 'All-Wheel Drive' },
      { icon: faCog, label: 'Condition', value: 'Used' },
      { icon: faTint, label: 'Cylinder', value: '6' },
      { icon: faTruck, label: 'Engine Size', value: '3.0L Turbocharged' },
      { icon: faTruck, label: 'Door', value: '4' },
      {
        icon: faPaintBrush,
        label: 'Color',
        value: 'Mineral White / Canberra Beige',
      },
      { icon: faFileAlt, label: 'VIN', value: '5UXKR0C53H0U53898' },
    ],
    features: {
      interior: [
        'Leather Seats',
        'Panoramic Moonroof',
        'Multi-Zone Climate Control',
        'Heated Front Seats',
        'Heads-Up Display',
        'Navigation System',
        'WiFi Hotspot',
        'Wireless Charging',
      ],
      safety: [
        'Back-up Camera',
        'Cross-Traffic Alert',
        'Rear Parking Aid',
        'Child Safety Locks',
        'Anti-lock Braking',
        'Traction Control',
        'Airbags (Front, Side, Curtain)',
      ],
      exterior: [
        'Fog Lamps',
        'HID Headlights',
        'Rain Sensing Wipers',
        'Power Liftgate',
        '20" Alloy Wheels',
        'Chrome Trim',
      ],
      comfortAndConvenience: [
        'Apple CarPlay',
        'Bluetooth',
        'Smart Device Integration',
        'Keyless Start',
        'Power Front Seats',
        'Seat Memory',
        'Garage Door Opener',
      ],
    },
  },
  {
    id: 2,
    name: '2024 Toyota Corolla LE',
    make: 'Toyota',
    model: 'Corolla',
    slug: '2024-toyota-corolla-le',
    description:
      'Reliable fuel-efficient sedan with modern tech and Toyota Safety Sense 3.0',
    price: '$—', // You can fill this in
    imageUrl: '/cars/car0.jpeg',
    images: [
      '/cars/car9.jpeg',
      '/cars/car2.jpeg',
      '/cars/car3.jpeg',
      '/cars/car4.jpeg',
      '/cars/car5.jpeg',
      '/cars/car6.jpeg',
      '/cars/car7.jpeg',
      '/cars/car8.jpeg',
      '/cars/car9.jpeg',
    ],
    body: 'Sedan',
    mileage: '22,595',
    fuelType: 'Gasoline',
    year: '2024',
    transmission: 'CVT',
    driveType: 'Front-Wheel Drive',
    condition: 'Used',
    cylinder: '4',
    engineSize: '2.0L 4-Cylinder',
    door: '4',
    color: 'Classic Silver / Black',
    vin: '5YFB4MDEXRP155846',
    attributes: [
      { icon: faCar, label: 'Body', value: 'Sedan' },
      { icon: faTachometerAlt, label: 'Mileage', value: '22,595 mi' },
      { icon: faGasPump, label: 'Fuel Type', value: 'Gasoline' },
      { icon: faCalendarAlt, label: 'Year', value: '2024' },
      { icon: faExchangeAlt, label: 'Transmission', value: 'CVT' },
      { icon: faCircle, label: 'Drive Type', value: 'Front-Wheel Drive' },
      { icon: faCog, label: 'Condition', value: 'Used' },
      { icon: faTint, label: 'Cylinder', value: '4' },
      { icon: faTruck, label: 'Engine Size', value: '2.0L 4-Cylinder' },
      { icon: faTruck, label: 'Door', value: '4' },
      { icon: faPaintBrush, label: 'Color', value: 'Classic Silver / Black' },
      { icon: faFileAlt, label: 'VIN', value: '5YFB4MDEXRP155846' },
    ],
    features: {
      interior: [
        'Fabric Upholstery',
        'Touchscreen Infotainment System',
        'Apple CarPlay & Android Auto',
        'Automatic Climate Control',
        '60/40 Split Rear Seats',
        'Rearview Camera',
      ],
      safety: [
        'Toyota Safety Sense 3.0',
        'Pre-Collision System',
        'Lane Departure Alert',
        'Dynamic Radar Cruise Control',
        'Backup Camera',
        'Automatic High Beams',
      ],
      exterior: [
        'LED Headlights',
        'Body-Colored Bumpers',
        'Power Side Mirrors',
        'Steel Wheels with Covers',
      ],
      comfortAndConvenience: [
        'Bluetooth Connectivity',
        'Keyless Entry',
        'USB Charging Ports',
        'Tilt & Telescopic Steering Wheel',
      ],
    },
  },

  {
    id: 3,
    name: '2006 Honda Accord LX',
    make: 'Honda',
    model: 'Accord',
    slug: '2006-honda-accord-lx',
    description:
      'Reliable and fuel-efficient sedan with low mileage and a smooth ride.',
    price: '$—', // Fill this in based on your asking price
    imageUrl: '/cars/car0.jpeg',
    images: [
      '/cars/car6.jpeg',
      '/cars/car5.jpeg',
      '/cars/car3.jpeg',
      '/cars/car4.jpeg',
      '/cars/car5.jpeg',
      '/cars/car6.jpeg',
      '/cars/car7.jpeg',
      '/cars/car8.jpeg',
      '/cars/car9.jpeg',
    ],
    body: 'Sedan',
    mileage: '11,958',
    fuelType: 'Gasoline',
    year: '2006',
    transmission: 'Automatic',
    driveType: 'Front-Wheel Drive',
    condition: 'Used',
    cylinder: '4',
    engineSize: '2.4L Inline-4',
    door: '4',
    color: 'Silver / Gray',
    vin: '1HGCM56306A044634',
    attributes: [
      { icon: faCar, label: 'Body', value: 'Sedan' },
      { icon: faTachometerAlt, label: 'Mileage', value: '11,958 mi' },
      { icon: faGasPump, label: 'Fuel Type', value: 'Gasoline' },
      { icon: faCalendarAlt, label: 'Year', value: '2006' },
      { icon: faExchangeAlt, label: 'Transmission', value: 'Automatic' },
      { icon: faCircle, label: 'Drive Type', value: 'Front-Wheel Drive' },
      { icon: faCog, label: 'Condition', value: 'Used' },
      { icon: faTint, label: 'Cylinder', value: '4' },
      { icon: faTruck, label: 'Engine Size', value: '2.4L Inline-4' },
      { icon: faTruck, label: 'Door', value: '4' },
      { icon: faPaintBrush, label: 'Color', value: 'Silver / Gray' },
      { icon: faFileAlt, label: 'VIN', value: '1HGCM56306A044634' },
    ],
    features: {
      interior: [
        'Cloth Upholstery',
        'Manual Adjustable Seats',
        'Air Conditioning',
        'Cruise Control',
        'CD Player',
        'Power Windows & Locks',
      ],
      safety: [
        'Front Airbags',
        'Side-Impact Airbags',
        'Anti-lock Braking System (ABS)',
        'Child Safety Locks',
      ],
      exterior: [
        'Halogen Headlights',
        'Body-Colored Mirrors',
        '15" Steel Wheels',
      ],
      comfortAndConvenience: [
        'Keyless Entry',
        'Tilt Steering Wheel',
        'AM/FM Radio',
        'Power Mirrors',
      ],
    },
  },

  {
    id: 5,
    name: '2015 Hyundai Sonata Sport',
    make: 'Hyundai',
    model: 'Sonata',
    slug: '2015-hyundai-sonata-sport',
    description:
      'Midsize sedan with sporty styling, great fuel efficiency, and a comfortable ride.',
    price: '$—', // Replace with your actual asking price
    imageUrl: '/cars/car0.jpeg',
    images: [
      '/cars/car6.jpeg',
      '/cars/car5.jpeg',
      '/cars/car3.jpeg',
      '/cars/car4.jpeg',
      '/cars/car5.jpeg',
      '/cars/car6.jpeg',
      '/cars/car7.jpeg',
      '/cars/car8.jpeg',
      '/cars/car9.jpeg',
    ],
    body: 'Sedan',
    mileage: '129,235',
    fuelType: 'Gasoline',
    year: '2015',
    transmission: 'Automatic',
    driveType: 'Front-Wheel Drive',
    condition: 'Used',
    cylinder: '4',
    engineSize: '2.4L Inline-4',
    door: '4',
    color: 'White / Black',
    vin: '5NPE34AFXFH106068',
    attributes: [
      { icon: faCar, label: 'Body', value: 'Sedan' },
      { icon: faTachometerAlt, label: 'Mileage', value: '129,235 mi' },
      { icon: faGasPump, label: 'Fuel Type', value: 'Gasoline' },
      { icon: faCalendarAlt, label: 'Year', value: '2015' },
      { icon: faExchangeAlt, label: 'Transmission', value: 'Automatic' },
      { icon: faCircle, label: 'Drive Type', value: 'Front-Wheel Drive' },
      { icon: faCog, label: 'Condition', value: 'Used' },
      { icon: faTint, label: 'Cylinder', value: '4' },
      { icon: faTruck, label: 'Engine Size', value: '2.4L Inline-4' },
      { icon: faTruck, label: 'Door', value: '4' },
      { icon: faPaintBrush, label: 'Color', value: 'White / Black' },
      { icon: faFileAlt, label: 'VIN', value: '5NPE34AFXFH106068' },
    ],
    features: {
      interior: [
        'Power Driver Seat',
        'Touchscreen Audio Display',
        'Bluetooth Hands-Free System',
        'Cloth Seats with Leather Bolsters',
        'Dual-Zone Climate Control',
        'Steering Wheel Controls',
      ],
      safety: [
        'Rearview Camera',
        'Stability Control',
        'Traction Control',
        'ABS',
        'Multiple Airbags',
        'Tire Pressure Monitoring System',
      ],
      exterior: [
        '18" Alloy Wheels',
        'LED Daytime Running Lights',
        'Projector Headlights',
        'Chrome Grille',
        'Power Side Mirrors with Turn Signal Indicators',
      ],
      comfortAndConvenience: [
        'Keyless Entry',
        'Cruise Control',
        'Power Windows & Locks',
        'USB & Auxiliary Ports',
        'Tilt-and-Telescopic Steering Wheel',
      ],
    },
  },

  {
    id: 8,
    name: '2007 Acura MDX',
    make: 'Acura',
    model: 'MDX',
    slug: '2007-acura-mdx',
    description:
      'Luxury AWD SUV with seating for seven, premium features, and advanced safety systems.',
    price: '$—', // Replace with your actual asking price
    imageUrl: '/cars/car0.jpeg',
    images: [
      '/cars/car9.jpeg',
      '/cars/car2.jpeg',
      '/cars/car3.jpeg',
      '/cars/car4.jpeg',
      '/cars/car5.jpeg',
      '/cars/car6.jpeg',
      '/cars/car7.jpeg',
      '/cars/car8.jpeg',
      '/cars/car9.jpeg',
    ],
    body: 'SUV',
    mileage: '127,476',
    fuelType: 'Gasoline',
    year: '2007',
    transmission: 'Automatic',
    driveType: 'All-Wheel Drive',
    condition: 'Used',
    cylinder: '6',
    engineSize: '3.7L V6',
    door: '4',
    color: 'Silver / Black',
    vin: '2HNYD28297H512137',
    attributes: [
      { icon: faCar, label: 'Body', value: 'SUV' },
      { icon: faTachometerAlt, label: 'Mileage', value: '127,476 mi' },
      { icon: faGasPump, label: 'Fuel Type', value: 'Gasoline' },
      { icon: faCalendarAlt, label: 'Year', value: '2007' },
      { icon: faExchangeAlt, label: 'Transmission', value: 'Automatic' },
      { icon: faCircle, label: 'Drive Type', value: 'All-Wheel Drive' },
      { icon: faCog, label: 'Condition', value: 'Used' },
      { icon: faTint, label: 'Cylinder', value: '6' },
      { icon: faTruck, label: 'Engine Size', value: '3.7L V6' },
      { icon: faTruck, label: 'Door', value: '4' },
      { icon: faPaintBrush, label: 'Color', value: 'Silver / Black' },
      { icon: faFileAlt, label: 'VIN', value: '2HNYD28297H512137' },
    ],
    features: {
      interior: [
        'Leather Upholstery',
        'Power Front Seats',
        'Heated Front Seats',
        'Tri-Zone Automatic Climate Control',
        'Navigation System (optional)',
        'Rear Entertainment System (optional)',
        'Bluetooth Connectivity',
      ],
      safety: [
        'Front, Side, and Curtain Airbags',
        'Anti-lock Braking System (ABS)',
        'Electronic Stability Control',
        'Traction Control',
        'Child Safety Locks',
        'Rearview Camera (if equipped)',
      ],
      exterior: [
        'Xenon HID Headlights',
        'Power Liftgate',
        '18" Alloy Wheels',
        'Fog Lamps',
        'Roof Rails',
      ],
      comfortAndConvenience: [
        'Keyless Entry',
        'Cruise Control',
        'Steering Wheel Audio Controls',
        'Memory Driver Seat',
        'Sunroof (optional)',
      ],
    },
  },
  {
    id: 5,
    name: '2015 Volkswagen Passat TDI SEL',
    make: 'Volkswagen',
    model: 'Passat',
    slug: '2015-volkswagen-passat-tdi-sel',
    description:
      'Fuel-efficient TDI diesel sedan with premium features and spacious interior.',
    price: '$8,900',
    imageUrl: '/cars/car0.jpeg',
    images: [
      '/cars/car9.jpeg',
      '/cars/car2.jpeg',
      '/cars/car3.jpeg',
      '/cars/car4.jpeg',
      '/cars/car5.jpeg',
      '/cars/car6.jpeg',
      '/cars/car7.jpeg',
      '/cars/car8.jpeg',
      '/cars/car9.jpeg',
    ],
    body: 'Sedan',
    mileage: '150,436',
    fuelType: 'Diesel',
    year: '2015',
    transmission: 'Automatic',
    driveType: 'Front-Wheel Drive',
    condition: 'Used',
    cylinder: '4',
    engineSize: '2.0L TDI Diesel',
    door: '4',
    color: 'Reflex Silver / Titan Black',
    vin: '1VWBV7A35FC031647',
    attributes: [
      { icon: 'faCar', label: 'Body', value: 'Sedan' },
      { icon: 'faTachometerAlt', label: 'Mileage', value: '150,436 mi' },
      { icon: 'faGasPump', label: 'Fuel Type', value: 'Diesel' },
      { icon: 'faCalendarAlt', label: 'Year', value: '2015' },
      { icon: 'faExchangeAlt', label: 'Transmission', value: 'Automatic' },
      { icon: 'faCircle', label: 'Drive Type', value: 'Front-Wheel Drive' },
      { icon: 'faCog', label: 'Condition', value: 'Used' },
      { icon: 'faTint', label: 'Cylinder', value: '4' },
      { icon: 'faTruck', label: 'Engine Size', value: '2.0L TDI Diesel' },
      { icon: 'faTruck', label: 'Door', value: '4' },
      {
        icon: 'faPaintBrush',
        label: 'Color',
        value: 'Reflex Silver / Titan Black',
      },
      { icon: 'faFileAlt', label: 'VIN', value: '1VWBV7A35FC031647' },
    ],
    features: {
      interior: [
        'Leatherette Seats',
        'Touchscreen Infotainment',
        'Heated Front Seats',
        'Dual-Zone Climate Control',
        'Navigation System',
        'Bluetooth Audio & Phone',
        'Fender Premium Audio',
      ],
      safety: [
        'Rearview Camera',
        'Anti-lock Braking System',
        'Stability Control',
        'Side Curtain Airbags',
        'Tire Pressure Monitor',
      ],
      exterior: [
        '17" Alloy Wheels',
        'Fog Lamps',
        'Heated Side Mirrors',
        'Chrome Exterior Trim',
      ],
      comfortAndConvenience: [
        'Keyless Entry',
        'Push Button Start',
        'Power Driver Seat',
        'Cruise Control',
        'Fold-Down Rear Seats',
        'USB & AUX Inputs',
      ],
    },
  },

  {
    id: 6,
    name: '2007 Lexus ES 350',
    make: 'Lexus',
    model: 'ES 350',
    slug: '2007-lexus-es-350',
    description:
      'Luxury mid-size sedan with refined comfort, smooth V6 performance, and premium features.',
    price: '$7,800',
    imageUrl: '/cars/car0.jpeg',
    images: [
      '/cars/car6.jpeg',
      '/cars/car5.jpeg',
      '/cars/car3.jpeg',
      '/cars/car4.jpeg',
      '/cars/car5.jpeg',
      '/cars/car6.jpeg',
      '/cars/car7.jpeg',
      '/cars/car8.jpeg',
      '/cars/car9.jpeg',
    ],
    body: 'Sedan',
    mileage: '122,420',
    fuelType: 'Gasoline',
    year: '2007',
    transmission: 'Automatic',
    driveType: 'Front-Wheel Drive',
    condition: 'Used',
    cylinder: '6',
    engineSize: '3.5L V6',
    door: '4',
    color: 'Matador Red Mica / Cashmere',
    vin: 'JTHBJ46G372006275',
    attributes: [
      { icon: 'faCar', label: 'Body', value: 'Sedan' },
      { icon: 'faTachometerAlt', label: 'Mileage', value: '122,420 mi' },
      { icon: 'faGasPump', label: 'Fuel Type', value: 'Gasoline' },
      { icon: 'faCalendarAlt', label: 'Year', value: '2007' },
      { icon: 'faExchangeAlt', label: 'Transmission', value: 'Automatic' },
      { icon: 'faCircle', label: 'Drive Type', value: 'Front-Wheel Drive' },
      { icon: 'faCog', label: 'Condition', value: 'Used' },
      { icon: 'faTint', label: 'Cylinder', value: '6' },
      { icon: 'faTruck', label: 'Engine Size', value: '3.5L V6' },
      { icon: 'faTruck', label: 'Door', value: '4' },
      {
        icon: 'faPaintBrush',
        label: 'Color',
        value: 'Matador Red Mica / Cashmere',
      },
      { icon: 'faFileAlt', label: 'VIN', value: 'JTHBJ46G372006275' },
    ],
    features: {
      interior: [
        'Leather Upholstery',
        'Power Adjustable Front Seats',
        'Dual-Zone Automatic Climate Control',
        'Wood Trim Accents',
        'Sunroof',
        'Premium Audio System',
        'Navigation System',
      ],
      safety: [
        'Anti-lock Braking System (ABS)',
        'Electronic Stability Control',
        'Front and Rear Side Curtain Airbags',
        'Tire Pressure Monitoring System',
        'Brake Assist',
      ],
      exterior: [
        '17" Alloy Wheels',
        'Fog Lamps',
        'Heated Side Mirrors',
        'Chrome Exterior Trim',
      ],
      comfortAndConvenience: [
        'Keyless Entry and Start',
        'Cruise Control',
        'Steering Wheel Mounted Controls',
        'Auto-Dimming Rearview Mirror',
        'HomeLink Universal Transceiver',
      ],
    },
  },
  {
    id: 7,
    name: '2023 Chevrolet Malibu 1LT',
    make: 'Chevrolet',
    model: 'Malibu',
    slug: '2023-chevrolet-malibu-1lt',
    description:
      'Modern mid-size sedan offering a comfortable ride, fuel efficiency, and advanced technology features.',
    price: '$17,980',
    imageUrl: '/cars/car0.jpeg',
    images: [
      '/cars/car2.jpeg',
      '/cars/car3.jpeg',
      '/cars/car3.jpeg',
      '/cars/car4.jpeg',
      '/cars/car5.jpeg',
      '/cars/car6.jpeg',
      '/cars/car7.jpeg',
      '/cars/car8.jpeg',
      '/cars/car9.jpeg',
    ],
    body: 'Sedan',
    mileage: '60,641',
    fuelType: 'Gasoline',
    year: '2023',
    transmission: 'Continuously Variable Transmission (CVT)',
    driveType: 'Front-Wheel Drive',
    condition: 'Used',
    cylinder: '4',
    engineSize: '1.5L Turbocharged',
    door: '4',
    color: 'Summit White / Jet Black',
    vin: '1G1ZDSST6PF206438',
    attributes: [
      { icon: 'faCar', label: 'Body', value: 'Sedan' },
      { icon: 'faTachometerAlt', label: 'Mileage', value: '60,641 mi' },
      { icon: 'faGasPump', label: 'Fuel Type', value: 'Gasoline' },
      { icon: 'faCalendarAlt', label: 'Year', value: '2023' },
      { icon: 'faExchangeAlt', label: 'Transmission', value: 'CVT' },
      { icon: 'faCircle', label: 'Drive Type', value: 'Front-Wheel Drive' },
      { icon: 'faCog', label: 'Condition', value: 'Used' },
      { icon: 'faTint', label: 'Cylinder', value: '4' },
      { icon: 'faTruck', label: 'Engine Size', value: '1.5L Turbocharged' },
      { icon: 'faTruck', label: 'Door', value: '4' },
      {
        icon: 'faPaintBrush',
        label: 'Color',
        value: 'Summit White / Jet Black',
      },
      { icon: 'faFileAlt', label: 'VIN', value: '1G1ZDSST6PF206438' },
    ],
    features: {
      interior: [
        'Premium Cloth Seats',
        '8-Way Power Driver Seat',
        'Dual-Zone Automatic Climate Control',
        'Leather-Wrapped Steering Wheel',
        '6-Speaker Audio System',
        '8-Inch Touchscreen Infotainment',
        'Apple CarPlay & Android Auto',
      ],
      safety: [
        'Rear Vision Camera',
        'Forward Collision Alert',
        'Automatic Emergency Braking',
        'Lane Keep Assist with Lane Departure Warning',
        'Front Pedestrian Braking',
        'Rear Park Assist',
        '10 Airbags',
      ],
      exterior: [
        '17" Aluminum Wheels',
        'LED Daytime Running Lamps',
        'Heated Power-Adjustable Side Mirrors',
        'Acoustic-Laminated Windshield',
      ],
      comfortAndConvenience: [
        'Keyless Open and Start',
        'Remote Start',
        'Cruise Control',
        'OnStar & Chevrolet Connected Services',
        'Wi-Fi Hotspot Capability',
        'USB Ports',
        'Bluetooth Connectivity',
      ],
    },
  },
];
