import {
  faCar,
  faTachometerAlt,
  faGasPump,
  faCalendarAlt,
  faExchangeAlt,
  faCircle,
  faCog,
  faTint,
  faTruck,
  faPaintBrush,
  faFileAlt,
} from '@fortawesome/free-solid-svg-icons';

export const CARS_DATA = [
  {
    id: 1,
    name: '2017 BMW X5 xDrive35i',
    make: 'BMW',
    model: 'X5',
    slug: '2017-bmw-x5-xdrive35i',
    description:
      'Luxury AWD SUV with 3rd Row, Panoramic Roof, Navigation & Premium Package',
    price: '$22,500',
    imageUrl: '/cars/car0.jpeg',
    images: [
      '/cars/car0.jpeg',
      '/cars/car2.jpeg',
      '/cars/car3.jpeg',
      '/cars/car4.jpeg',
      '/cars/car5.jpeg',
      '/cars/car6.jpeg',
      '/cars/car7.jpeg',
      '/cars/car8.jpeg',
      '/cars/car9.jpeg',
    ],
    body: 'SUV',
    mileage: '113,388',
    fuelType: 'Gasoline',
    year: '2017',
    transmission: 'Automatic',
    driveType: 'All-Wheel Drive',
    condition: 'Used',
    cylinder: '6',
    engineSize: '3.0L Turbocharged',
    door: '4',
    color: 'Mineral White / Canberra Beige',
    vin: '5UXKR0C53H0U53898',
    attributes: [
      { icon: faCar, label: 'Body', value: 'SUV' },
      { icon: faTachometerAlt, label: 'Mileage', value: '113,388 mi' },
      { icon: faGasPump, label: 'Fuel Type', value: 'Gasoline' },
      { icon: faCalendarAlt, label: 'Year', value: '2017' },
      { icon: faExchangeAlt, label: 'Transmission', value: 'Automatic' },
      { icon: faCircle, label: 'Drive Type', value: 'All-Wheel Drive' },
      { icon: faCog, label: 'Condition', value: 'Used' },
      { icon: faTint, label: 'Cylinder', value: '6' },
      { icon: faTruck, label: 'Engine Size', value: '3.0L Turbocharged' },
      { icon: faTruck, label: 'Door', value: '4' },
      {
        icon: faPaintBrush,
        label: 'Color',
        value: 'Mineral White / Canberra Beige',
      },
      { icon: faFileAlt, label: 'VIN', value: '5UXKR0C53H0U53898' },
    ],
    features: {
      interior: [
        'Leather Seats',
        'Panoramic Moonroof',
        'Multi-Zone Climate Control',
        'Heated Front Seats',
        'Heads-Up Display',
        'Navigation System',
        'WiFi Hotspot',
        'Wireless Charging',
      ],
      safety: [
        'Back-up Camera',
        'Cross-Traffic Alert',
        'Rear Parking Aid',
        'Child Safety Locks',
        'Anti-lock Braking',
        'Traction Control',
        'Airbags (Front, Side, Curtain)',
      ],
      exterior: [
        'Fog Lamps',
        'HID Headlights',
        'Rain Sensing Wipers',
        'Power Liftgate',
        '20" Alloy Wheels',
        'Chrome Trim',
      ],
      comfortAndConvenience: [
        'Apple CarPlay',
        'Bluetooth',
        'Smart Device Integration',
        'Keyless Start',
        'Power Front Seats',
        'Seat Memory',
        'Garage Door Opener',
      ],
    },
  },
  {
    id: 2,
    name: '2020 Toyota Camry SE',
    make: 'Toyota',
    model: 'Camry',
    slug: '2020-toyota-camry-se',
    description:
      'Sporty sedan with advanced safety features and great fuel economy.',
    price: '$19,900',
    imageUrl: '/cars/car0.jpeg',
    images: [
      '/cars/car9.jpeg',
      '/cars/car2.jpeg',
      '/cars/car3.jpeg',
      '/cars/car4.jpeg',
      '/cars/car5.jpeg',
      '/cars/car6.jpeg',
      '/cars/car7.jpeg',
      '/cars/car8.jpeg',
      '/cars/car9.jpeg',
    ],
    body: 'Sedan',
    mileage: '32,500',
    fuelType: 'Petrol',
    year: '2020',
    transmission: 'Automatic',
    driveType: 'Front-Wheel Drive',
    condition: 'Used',
    cylinder: '4',
    engineSize: '2.5L',
    door: '4',
    color: 'Super White',
    vin: '4T1G11AK0LU123456',
    attributes: [
      { icon: faCar, label: 'Body', value: 'Sedan' },
      { icon: faTachometerAlt, label: 'Mileage', value: '32,500 mi' },
      { icon: faGasPump, label: 'Fuel Type', value: 'Petrol' },
      { icon: faCalendarAlt, label: 'Year', value: '2020' },
      { icon: faExchangeAlt, label: 'Transmission', value: 'Automatic' },
      { icon: faCircle, label: 'Drive Type', value: 'Front-Wheel Drive' },
      { icon: faCog, label: 'Condition', value: 'Used' },
      { icon: faTint, label: 'Cylinder', value: '4' },
      { icon: faTruck, label: 'Engine Size', value: '2.5L' },
      { icon: faTruck, label: 'Door', value: '4' },
      { icon: faPaintBrush, label: 'Color', value: 'Super White' },
      { icon: faFileAlt, label: 'VIN', value: '4T1G11AK0LU123456' },
    ],
    features: {
      interior: [
        'Fabric Seats',
        'Power Driver Seat',
        'Dual Zone Climate Control',
        'Touchscreen Display',
        'Bluetooth',
        'Backup Camera',
      ],
      safety: [
        'Lane Departure Alert',
        'Adaptive Cruise Control',
        'Pre-Collision System',
        'Blind Spot Monitor',
        'Brake Assist',
      ],
      exterior: [
        'LED Headlights',
        'Alloy Wheels',
        'Heated Mirrors',
        'Rear Spoiler',
      ],
      comfortAndConvenience: [
        'Remote Keyless Entry',
        'Push Button Start',
        'Apple CarPlay',
        'Android Auto',
      ],
    },
  },
  {
    id: 3,
    name: '2019 Honda Accord LX',
    make: 'Honda',
    model: 'Accord',
    slug: '2019-honda-accord-lx',
    description:
      'Reliable sedan with spacious interior and advanced driver-assist features.',
    price: '$18,400',
    imageUrl: '/cars/car0.jpeg',
    images: [
      '/cars/car6.jpeg',
      '/cars/car5.jpeg',
      '/cars/car3.jpeg',
      '/cars/car4.jpeg',
      '/cars/car5.jpeg',
      '/cars/car6.jpeg',
      '/cars/car7.jpeg',
      '/cars/car8.jpeg',
      '/cars/car9.jpeg',
    ],
    body: 'Sedan',
    mileage: '28,900',
    fuelType: 'Petrol',
    year: '2019',
    transmission: 'CVT',
    driveType: 'Front-Wheel Drive',
    condition: 'Used',
    cylinder: '4',
    engineSize: '1.5L Turbo',
    door: '4',
    color: 'Modern Steel Metallic',
    vin: '1HGCV1F10KA123456',
    attributes: [
      { icon: faCar, label: 'Body', value: 'Sedan' },
      { icon: faTachometerAlt, label: 'Mileage', value: '28,900 mi' },
      { icon: faGasPump, label: 'Fuel Type', value: 'Petrol' },
      { icon: faCalendarAlt, label: 'Year', value: '2019' },
      { icon: faExchangeAlt, label: 'Transmission', value: 'CVT' },
      { icon: faCircle, label: 'Drive Type', value: 'Front-Wheel Drive' },
      { icon: faCog, label: 'Condition', value: 'Used' },
      { icon: faTint, label: 'Cylinder', value: '4' },
      { icon: faTruck, label: 'Engine Size', value: '1.5L Turbo' },
      { icon: faTruck, label: 'Door', value: '4' },
      { icon: faPaintBrush, label: 'Color', value: 'Modern Steel Metallic' },
      { icon: faFileAlt, label: 'VIN', value: '1HGCV1F10KA123456' },
    ],
    features: {
      interior: [
        'Cloth Seats',
        'Dual-Zone Climate Control',
        'Bluetooth',
        'Backup Camera',
        'Touchscreen Display',
      ],
      safety: [
        'Collision Mitigation Braking',
        'Road Departure Mitigation',
        'Lane Keeping Assist',
        'Adaptive Cruise Control',
      ],
      exterior: ['LED Headlights', 'Alloy Wheels', 'Power Mirrors'],
      comfortAndConvenience: [
        'Remote Start',
        'Keyless Entry',
        'Apple CarPlay',
        'Android Auto',
      ],
    },
  },
  {
    id: 4,
    name: '2021 Tesla Model 3 Standard Range Plus',
    make: 'Tesla',
    model: 'Model 3',
    slug: '2021-tesla-model-3-standard-range-plus',
    description:
      'All-electric sedan with Autopilot, premium sound, and long range.',
    price: '$35,900',
    imageUrl: '/cars/car0.jpeg',
    images: [
      '/cars/car4.jpeg',
      '/cars/car5.jpeg',
      '/cars/car3.jpeg',
      '/cars/car4.jpeg',
    ],
    body: 'Sedan',
    mileage: '15,200',
    fuelType: 'Electric',
    year: '2021',
    transmission: 'Automatic',
    driveType: 'Rear-Wheel Drive',
    condition: 'Used',
    cylinder: 'N/A',
    engineSize: 'Electric',
    door: '4',
    color: 'Pearl White Multi-Coat',
    vin: '5YJ3E1EA7MF123456',
    attributes: [
      { icon: faCar, label: 'Body', value: 'Sedan' },
      { icon: faTachometerAlt, label: 'Mileage', value: '15,200 mi' },
      { icon: faGasPump, label: 'Fuel Type', value: 'Electric' },
      { icon: faCalendarAlt, label: 'Year', value: '2021' },
      { icon: faExchangeAlt, label: 'Transmission', value: 'Automatic' },
      { icon: faCircle, label: 'Drive Type', value: 'Rear-Wheel Drive' },
      { icon: faCog, label: 'Condition', value: 'Used' },
      { icon: faTint, label: 'Cylinder', value: 'N/A' },
      { icon: faTruck, label: 'Engine Size', value: 'Electric' },
      { icon: faTruck, label: 'Door', value: '4' },
      { icon: faPaintBrush, label: 'Color', value: 'Pearl White Multi-Coat' },
      { icon: faFileAlt, label: 'VIN', value: '5YJ3E1EA7MF123456' },
    ],
    features: {
      interior: [
        'Vegan Leather Seats',
        'Panoramic Glass Roof',
        'Premium Audio',
        'Heated Front & Rear Seats',
        'Touchscreen Display',
      ],
      safety: [
        'Autopilot',
        'Automatic Emergency Braking',
        'Blind Spot Monitoring',
        'Lane Departure Warning',
      ],
      exterior: ['LED Fog Lamps', 'Aero Wheels', 'Power Folding Mirrors'],
      comfortAndConvenience: [
        'Keyless Entry',
        'Wireless Phone Charging',
        'Navigation',
        'Heated Steering Wheel',
      ],
    },
  },
  {
    id: 5,
    name: '2018 Mercedes-Benz C300 4MATIC',
    make: 'Mercedes-Benz',
    model: 'C300',
    slug: '2018-mercedes-benz-c300-4matic',
    description:
      'Luxury compact sedan with AWD, sunroof, and advanced safety tech.',
    price: '$27,800',
    imageUrl: '/cars/car0.jpeg',
    images: [
      '/cars/car2.jpeg',
      '/cars/car3.jpeg',
      '/cars/car3.jpeg',
      '/cars/car4.jpeg',
      '/cars/car5.jpeg',
      '/cars/car6.jpeg',
      '/cars/car7.jpeg',
      '/cars/car8.jpeg',
      '/cars/car9.jpeg',
    ],
    body: 'Sedan',
    mileage: '41,000',
    fuelType: 'Gasoline',
    year: '2018',
    transmission: 'Automatic',
    driveType: 'All-Wheel Drive',
    condition: 'Used',
    cylinder: '4',
    engineSize: '2.0L Turbo',
    door: '4',
    color: 'Polar White',
    vin: 'WDDWF4KB0JR123456',
    attributes: [
      { icon: faCar, label: 'Body', value: 'Sedan' },
      { icon: faTachometerAlt, label: 'Mileage', value: '41,000 mi' },
      { icon: faGasPump, label: 'Fuel Type', value: 'Gasoline' },
      { icon: faCalendarAlt, label: 'Year', value: '2018' },
      { icon: faExchangeAlt, label: 'Transmission', value: 'Automatic' },
      { icon: faCircle, label: 'Drive Type', value: 'All-Wheel Drive' },
      { icon: faCog, label: 'Condition', value: 'Used' },
      { icon: faTint, label: 'Cylinder', value: '4' },
      { icon: faTruck, label: 'Engine Size', value: '2.0L Turbo' },
      { icon: faTruck, label: 'Door', value: '4' },
      { icon: faPaintBrush, label: 'Color', value: 'Polar White' },
      { icon: faFileAlt, label: 'VIN', value: 'WDDWF4KB0JR123456' },
    ],
    features: {
      interior: [
        'MB-Tex Upholstery',
        'Power Front Seats',
        'Sunroof',
        'Dual-Zone Climate Control',
        'Heated Front Seats',
      ],
      safety: [
        'Collision Prevention Assist',
        'Blind Spot Assist',
        'Rearview Camera',
        'Rain Sensing Wipers',
      ],
      exterior: ['LED Headlamps', 'Alloy Wheels', 'Power Mirrors'],
      comfortAndConvenience: [
        'Keyless Go',
        'Bluetooth',
        'Navigation',
        'Apple CarPlay',
      ],
    },
  },
];
